<a href="https://colab.research.google.com/github/devpatel0005/TechMicra-AIML-Summer-Internship/blob/main/Stock_Sentiment_Analysis_and_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/devpatel0005/TechMicra-AIML-Summer-Internship/refs/heads/main/Datasets/Sentiment_Stock_data.csv')
df.sample(5)

,Unnamed: 0,Sentiment,Sentence
26300,27281,0,Health and social care directorates abolished
97446,99987,1,Soldiers Killed in Suicide Attack at U.S. Base...
25164,26118,0,Science and research will help Britain prosper...
24701,25633,0,Irish venture to the back of beyond
94590,97131,0,"1/4 of Europe's Bumblebees, Vital to Crops, Fa..."

In [3]:
df.isnull().sum()

Unnamed: 0    0
Sentiment     0
Sentence      1
dtype: int64

In [4]:
df.dropna()

,Unnamed: 0,Sentiment,Sentence
0,0,0,"According to Gran , the company has no plans t..."
1,1,1,"For the last quarter of 2010 , Componenta 's n..."
2,2,1,"In the third quarter of 2010 , net sales incre..."
3,3,1,Operating profit rose to EUR 13.1 mn from EUR ...
4,4,1,"Operating profit totalled EUR 21.1 mn , up fro..."
...,...,...,...
108746,111290,1,Philippines president Rodrigo Duterte urges pe...
108747,111291,1,Spain arrests three Pakistanis accused of prom...
108748,111292,1,"Venezuela, where anger over food shortages is ..."
108749,111293,1,A Hindu temple worker has been killed by three...
108750,111294,1,Ozone layer hole seems to be healing - US &amp...

In [5]:
df.drop_duplicates()

,Unnamed: 0,Sentiment,Sentence
0,0,0,"According to Gran , the company has no plans t..."
1,1,1,"For the last quarter of 2010 , Componenta 's n..."
2,2,1,"In the third quarter of 2010 , net sales incre..."
3,3,1,Operating profit rose to EUR 13.1 mn from EUR ...
4,4,1,"Operating profit totalled EUR 21.1 mn , up fro..."
...,...,...,...
108746,111290,1,Philippines president Rodrigo Duterte urges pe...
108747,111291,1,Spain arrests three Pakistanis accused of prom...
108748,111292,1,"Venezuela, where anger over food shortages is ..."
108749,111293,1,A Hindu temple worker has been killed by three...
108750,111294,1,Ozone layer hole seems to be healing - US &amp...

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108751 entries, 0 to 108750
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  108751 non-null  int64
 1   Sentiment   108751 non-null  int64
 2   Sentence    108750 non-null  object
dtypes: int64(2), object(1)
memory usage: 2.5+ MB